robots:
  - robot_type: "security"
    move_speed: 1.0
    perception_radius: 1.5
    obstacle_distance_threshold: 1.0
    start_x: 13.0
    start_y: 6.0
    end_x: 2.0
    end_y: 6.0
    path: 
      - [13.0, 6.0]
      - [2.0, 6.0]
      - [2.0, 2.0]
      - [13.0, 2.0]
    loop: true

  - robot_type: "cleaner"
    move_speed: 1.0
    perception_radius: 1.5
    obstacle_distance_threshold: 1.0
    start_x: 2.0
    start_y: 2.0
    end_x: 13.0
    end_y: 2.0
    path: 
      - [2.0, 2.0]
      - [13.0, 2.0]
      - [13.0, 6.0]
      - [2.0, 6.0]
    loop: true