robots:
  - robot_type: "security"
    move_speed: 2.0
    perception_radius: 0.5
    obstacle_distance_threshold: 2.0
    start_x: 7.0
    start_y: 1.0
    start_z: 6.0
    end_x: 7.0
    end_y: 1.0
    end_z: 12.0
    path: 
      - [7.0, 1.0, 6.0]
      - [7.0, 1.0, 12.0]
      - [2.0, 1.0, 12.0]
      - [2.0, 1.0, 6.0]
    loop: true

  - robot_type: "cleaner"
    move_speed: 2.0
    perception_radius: 0.5
    obstacle_distance_threshold: 2.0
    start_x: 2.0
    start_y: 1.0
    start_z: 2.0
    end_x: 13.0
    end_y: 1.0
    end_z: 2.0
    path: 
      - [2.0, 1.0, 2.0]
      - [13.0, 1.0, 2.0]
      - [13.0, 1.0, 6.0]
      - [2.0, 1.0, 6.0]
    loop: true

  - robot_type: "cleaner"
    move_speed: 2.0
    perception_radius: 0.5
    obstacle_distance_threshold: 2.0
    start_x: 20.0
    start_y: 1.0
    start_z: 27.0
    end_x: 20.0
    end_y: 1.0
    end_z: 19.0
    path: 
      - [20.0, 1.0, 27.0]
      - [20.0, 1.0, 19.0]
      - [27.0, 1.0, 19.0]
      - [27.0, 1.0, 27.0]
    loop: true

  - robot_type: "cleaner"
    move_speed: 2.0
    perception_radius: 0.5
    obstacle_distance_threshold: 2.0
    start_x: 2.0
    start_y: 1.0
    start_z: 27.0
    end_x: 2.0
    end_y: 1.0
    end_z: 12.0
    path: 
      - [2.0, 1.0, 27.0]
      - [2.0, 1.0, 12.0]
      - [7.0, 1.0, 12.0]
      - [7.0, 1.0, 27.0]
    loop: true

  - robot_type: "cleaner"
    move_speed: 2.0
    perception_radius: 0.5
    obstacle_distance_threshold: 2.0
    start_x: 27.0
    start_y: 1.0
    start_z: 7.0
    end_x: 20.0
    end_y: 1.0
    end_z: 7.0
    path: 
      - [27.0, 1.0, 7.0]
      - [20.0, 1.0, 7.0]
      - [20.0, 1.0, 2.0]
      - [27.0, 1.0, 2.0]
    loop: true
  
  - robot_type: "baggage"
    move_speed: 2.0
    perception_radius: 0.5
    obstacle_distance_threshold: 2.0
    start_x: 28.0
    start_y: 1.0
    start_z: 12.0
    end_x: 1.0
    end_y: 1.0
    end_z: 12.0
    path: 
      - [28.0, 1.0, 12.0]
      - [1.0, 1.0, 12.0]
    loop: true