nodes:
  - id: 0
    x: 1
    y: 1
  - id: 1
    x: 1
    y: 2
  - id: 2
    x: 1
    y: 3
  - id: 3
    x: 1
    y: 4
  - id: 4
    x: 1
    y: 5
  - id: 5
    x: 1
    y: 6
  - id: 6
    x: 1
    y: 7
  - id: 7
    x: 1
    y: 8
  - id: 8
    x: 2
    y: 8
  - id: 9
    x: 3
    y: 8
  - id: 10
    x: 4
    y: 8
  - id: 11
    x: 5
    y: 8
  - id: 12
    x: 6
    y: 8
  - id: 13
    x: 7
    y: 8
  - id: 14
    x: 8
    y: 8
  - id: 15
    x: 9
    y: 8
  - id: 16
    x: 9
    y: 7
  - id: 17
    x: 9
    y: 6
  - id: 18
    x: 9
    y: 5
  - id: 19
    x: 9
    y: 4
  - id: 20
    x: 9
    y: 3
  - id: 21
    x: 9
    y: 2
  - id: 22
    x: 9
    y: 1
  - id: 23
    x: 2
    y: 3
  - id: 24
    x: 3
    y: 3
  - id: 25
    x: 4
    y: 3
  - id: 26
    x: 5
    y: 3
  - id: 27
    x: 6
    y: 3
  - id: 28
    x: 6
    y: 4
  - id: 29
    x: 6
    y: 5
  - id: 30
    x: 6
    y: 6
  - id: 31
    x: 5
    y: 6
  - id: 32
    x: 4
    y: 6
  - id: 33
    x: 3
    y: 6
  - id: 34
    x: 2
    y: 6
  - id: 35
    x: 6
    y: 7
  - id: 36
    x: 2
    y: 1
  - id: 37
    x: 3
    y: 1
  - id: 38
    x: 4
    y: 1
  - id: 39
    x: 5
    y: 1
  - id: 40
    x: 6
    y: 1
  - id: 41
    x: 7
    y: 1
  - id: 42
    x: 8
    y: 1
  - id: 43
    x: 4
    y: 2
adjacency:
  0: [ 1, 36 ]
  1: [ 0, 2 ]
  2: [ 1, 3, 23 ]
  3: [ 2, 4 ]
  4: [ 3, 5 ]
  5: [ 4, 6, 34 ]
  6: [ 5, 7 ]
  7: [ 6, 8 ]
  8: [ 7, 9 ]
  9: [ 8, 10 ]
  10: [ 9, 11 ]
  11: [ 10, 12 ]
  12: [ 11, 13, 35 ]
  13: [ 12, 14 ]
  14: [ 13, 15 ]
  15: [ 14, 16 ]
  16: [ 15, 17 ]
  17: [ 16, 18 ]
  18: [ 17, 19 ]
  19: [ 18, 20 ]
  20: [ 19, 21 ]
  21: [ 20, 22 ]
  22: [ 21, 42 ]
  23: [ 2, 24 ]
  24: [ 23, 25 ]
  25: [ 24, 26, 43 ]
  26: [ 25, 27 ]
  27: [ 26, 28 ]
  28: [ 27, 29 ]
  29: [ 28, 30 ]
  30: [ 29, 31, 35 ]
  31: [ 30, 32 ]
  32: [ 31, 33 ]
  33: [ 32, 34 ]
  34: [ 5, 33 ]
  35: [ 12, 30 ]
  36: [ 0, 37 ]
  37: [ 36, 38 ]
  38: [ 37, 39, 43 ]
  39: [ 38, 40 ]
  40: [ 39, 41 ]
  41: [ 40, 42 ]
  42: [ 22, 41 ]
  43: [ 25, 38 ]
